### ISSUE TITLE
Ported to arduino

### ISSUE THREAD

**Issue by zignig** [therustybits/zero-to-async#2]
Thanks for the videos. You have a great presenting style. 

This encouraged me to port chapter 6 to Arduino AVR. 

main project:

https://github.com/zignig/steves_brain/tree/main/rover/newdrive-async

cleaned:

https://github.com/zignig/avr_async

I also changed the executor to a bit map rather than a queue (like lilos).

good stuff. ;)

**Comment by chrissuozzo** [comment]
Awesome, nice work!

**Comment by zignig** [comment]
coding continues.
